=== CypherNinjaa/yt-script/exams/web-dev/XML/XML_PRACTICE/students.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (roll,name,email,mobile)>
<!ELEMENT roll (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>

=== CypherNinjaa/yt-script/exams/web-dev/XML/XML_PRACTICE/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<students>
    <student>
        <roll>010</roll>
        <name>vikash</name>
        <email>Vikash@example.com</email>
        <mobile>+919199697225</mobile>
    </student>
    <student>
        <roll>010</roll>
        <name>vikash</name>
        <email>Vikash@example.com</email>
        <mobile>+919199697225</mobile>
    </student>
</students>

=== CypherNinjaa/yt-script/exams/web-dev/XML/Student.xml
<?xml version ="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
    <student>
        <roll>101</roll>
        <name>Vikash</name>
        <email>Vikashkell@example.com</email>
        <mobile>9199697225</mobile>
    </student>
    <student>
        <roll>102</roll>
        <name>Priya</name>
        <email>priya@gmail.com</email>
        <mobile>9123456789</mobile>
    </student>
</students>
